/** Login actions **/
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGIN_CAN_SUBMIT = 'LOGIN_CAN_SUBMIT';
export const LOGIN_SET_ERRORS = 'LOGIN_SET_ERRORS';

/** Check user actions **/
export const CHECK_USER_REQUEST = 'CHECK_USER_REQUEST';
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS';
export const CHECK_USER_FAILURE = 'CHECK_USER_FAILURE';

/** Registration actions **/
export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';

export const REGISTRATION_CAN_SUBMIT = 'REGISTRATION_CAN_SUBMIT';
export const REGISTRATION_SET_ERRORS = 'REGISTRATION_SET_ERRORS';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';


export const ADD_ITEMS_INTO_HOME_LIST = 'ADD_ITEMS_INTO_HOME_LIST';

